old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    consumers:
        accounting_user_stream:
            connection: default
            exchange_options: { name: user, type: topic }
            queue_options:
                name: accounting_user_stream_qu
                routing_keys:
                    - 'user_stream'
            callback: Accounting\Consumer\UserStreamConsumer
